import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy | copybanana",
  description: "How copybanana (Jianbo Ying) collects, uses, and protects your data.",
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen py-16">
      <div className="container px-4">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-3xl md:text-4xl font-bold mb-6">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: 29 Oct 2025</p>

          <div className="prose prose-neutral max-w-none text-left">
            <p>
              This Privacy Policy explains how copybanana ("we", "us", or the "Service") operated by <strong>Jianbo Ying</strong>
              at <strong>Room 602, No. 7 Longbai Fourth Village, Minhang District, Shanghai</strong> collects, uses, and
              shares information when you visit our site or use our AI image editing features.
            </p>

            <h2>1. Information We Collect</h2>
            <ul>
              <li>
                Account Data: email address, profile name, and identifiers supplied by third‑party sign‑in providers (e.g.,
                Google/GitHub).
              </li>
              <li>
                Content Data: prompts, reference images you upload, and outputs generated by the Service.
              </li>
              <li>
                Technical & Usage Data: device/browser information, IP address, country/region, pages viewed, actions
                taken, timestamps, and diagnostics for performance and abuse prevention.
              </li>
              <li>
                Billing Data: records from payment processors for purchases or subscriptions. We do not store complete
                card details on our servers.
              </li>
            </ul>

            <h2>2. How We Use Information</h2>
            <ul>
              <li>Operate, maintain, and secure the Service, including generating requested outputs.</li>
              <li>Improve quality, reliability, and safety of models and infrastructure.</li>
              <li>Provide support, communicate updates, and handle billing.</li>
              <li>Detect, investigate, and prevent fraud, abuse, and policy violations.</li>
              <li>Comply with legal obligations and enforce our Terms of Service.</li>
            </ul>

            <h2>3. Legal Bases</h2>
            <p>
              Where required, we process personal data based on consent, contract performance, legitimate interests
              (service improvement, security), or compliance with law.
            </p>

            <h2>4. Sharing and Disclosure</h2>
            <p>
              We share information with vendors that provide hosting, analytics, authentication, content delivery, model
              inference, and payment processing. Vendors act under contracts requiring confidentiality and appropriate
              security. Information may also be disclosed to authorities where required by law or to protect users and our
              rights.
            </p>

            <h2>5. Data Retention</h2>
            <p>
              We keep data as long as needed to provide the Service and for legitimate business needs (security, audit,
              accounting). Backups may persist for a limited period. You can request deletion of account data; some
              technical records may be retained as permitted by law.
            </p>

            <h2>6. International Transfers</h2>
            <p>
              Data may be processed in countries outside your own. Where applicable, we apply appropriate safeguards for
              such transfers.
            </p>

            <h2>7. Security</h2>
            <p>
              We use administrative, technical, and physical safeguards proportionate to the risk. No method of
              transmission or storage is completely secure.
            </p>

            <h2>8. Your Rights</h2>
            <ul>
              <li>Access, correction, deletion, or export of certain personal data.</li>
              <li>Withdrawal of consent where processing is based on consent.</li>
              <li>Objection or restriction, where applicable by law.</li>
            </ul>
            <p>To exercise rights, contact us using the details below.</p>

            <h2>9. Cookies and Similar Technologies</h2>
            <p>
              We use cookies and local storage for authentication, preferences, analytics, and security. You can control
              cookies via your browser; some features may not function if disabled.
            </p>

            <h2>10. Children</h2>
            <p>
              The Service is not intended for children under 13 (or the minimum age required by local law). We do not
              knowingly collect data from children.
            </p>

            <h2>11. Contact</h2>
            <p>
              Operator: <strong>Jianbo Ying</strong> · Address: <strong>Room 602, No. 7 Longbai Fourth Village, Minhang District, Shanghai</strong><br />
              Email: <a href="mailto:support@boboshixiong.com" className="underline">support@boboshixiong.com</a> · Phone: <a href="tel:+8618621994917" className="underline">+86 18621994917</a>
            </p>

            <h2>12. Changes to This Policy</h2>
            <p>
              We may revise this Privacy Policy from time to time. The updated version will be posted here with a new
              “Last updated” date.
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}
